#:schema node_modules/wrangler/config-schema.json
name = "cloudcart"
main = "src/index.ts"
compatibility_date = "2024-06-20"

[[kv_namespaces]]
binding = "CARTS"
id = "86943d725290455784202e1ea46dc11e"